-- AlterTable
ALTER TABLE `user` ADD COLUMN `birthday` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `firstName` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `lastName` VARCHAR(191) NOT NULL DEFAULT '';
